name: Deploy Telegram Bot

on:
  push:
    branches:
      - master # Сценарий срабатывает при каждом push в ветку main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm' # Ускоряет повторные сборки

      - name: Install dependencies
        run: npm ci

      # Если у вас написаны тесты, раскомментируйте строчку ниже:
      # - run: npm test

  deploy:
    needs: build-and-test # Деплой начнется только если сборка прошла успешно
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 1288
          script: |
            source /home/mrcoachb/nodevenv/telegramBOT/20/bin/activate && cd /home/mrcoachb/telegramBOT
            git pull origin master
            npm install --production
            pm2 restart tgbot
